/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type OnetOccupationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "onetOccupation";
};

export type OnetRelatedOccupationItem = {
  _type: "onetRelatedOccupationItem";
  occupation?: OnetOccupationReference;
  relatednessTier?: "Primary-Short" | "Primary-Long" | "Supplemental";
  relatedIndex?: number;
};

export type OnetContentModelElementReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "onetContentModelElement";
};

export type OnetScaleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "onetScale";
};

export type OnetRatingCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "onetRatingCategory";
};

export type OnetRatingItem = {
  _type: "onetRatingItem";
  domain?:
    | "essentialSkills"
    | "transferableSkills"
    | "knowledge"
    | "abilities"
    | "workActivities"
    | "education"
    | "workContext";
  element?: OnetContentModelElementReference;
  scale?: OnetScaleReference;
  ratingCategory?: OnetRatingCategoryReference;
  dataValue?: number;
  n?: number;
  standardError?: number;
  lowerCiBound?: number;
  upperCiBound?: number;
  recommendSuppress?: "Y" | "N";
  notRelevant?: "Y" | "N";
  dateUpdated?: string;
  domainSource?: string;
};

export type OnetWorkStyleItem = {
  _type: "onetWorkStyleItem";
  element?: OnetContentModelElementReference;
  scale?: OnetScaleReference;
  dataValue?: number;
  dateUpdated?: string;
  domainSource?: string;
};

export type OnetSoftwareSkillItem = {
  _type: "onetSoftwareSkillItem";
  workplaceExample?: string;
  element?: OnetContentModelElementReference;
  hotTechnology?: "Y" | "N";
  inDemand?: "Y" | "N";
};

export type OnetJobTitleItem = {
  _type: "onetJobTitleItem";
  jobTitle?: string;
  shortTitle?: string;
  sources?: string;
};

export type OnetTaskItem = {
  _type: "onetTaskItem";
  taskId?: number;
  task?: string;
  taskType?: "Core" | "Supplemental";
  incumbentsResponding?: number;
  dateUpdated?: string;
  domainSource?: string;
};

export type OnetJobZoneReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "onetJobZone";
};

export type OnetOccupation = {
  _id: string;
  _type: "onetOccupation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  onetsocCode?: string;
  title?: string;
  description?: string;
  jobZone?: OnetJobZoneReference;
  tasks?: Array<
    {
      _key: string;
    } & OnetTaskItem
  >;
  jobTitles?: Array<
    {
      _key: string;
    } & OnetJobTitleItem
  >;
  softwareSkills?: Array<
    {
      _key: string;
    } & OnetSoftwareSkillItem
  >;
  workStyles?: Array<
    {
      _key: string;
    } & OnetWorkStyleItem
  >;
  ratings?: Array<
    {
      _key: string;
    } & OnetRatingItem
  >;
  relatedOccupations?: Array<
    {
      _key: string;
    } & OnetRelatedOccupationItem
  >;
};

export type OnetLevelScaleAnchor = {
  _id: string;
  _type: "onetLevelScaleAnchor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  element?: OnetContentModelElementReference;
  scale?: OnetScaleReference;
  anchorValue?: number;
  anchorDescription?: string;
};

export type OnetRatingCategory = {
  _id: string;
  _type: "onetRatingCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  categoryDomain?: "education" | "workContext";
  element?: OnetContentModelElementReference;
  scale?: OnetScaleReference;
  category?: number;
  categoryDescription?: string;
};

export type OnetJobZone = {
  _id: string;
  _type: "onetJobZone";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  jobZone?: number;
  name?: string;
  experience?: string;
  education?: string;
  jobTraining?: string;
  examples?: string;
  svpRange?: string;
};

export type OnetScale = {
  _id: string;
  _type: "onetScale";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  scaleId?: string;
  scaleName?: string;
  minimum?: number;
  maximum?: number;
};

export type OnetContentModelElement = {
  _id: string;
  _type: "onetContentModelElement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  importKey?: string;
  elementId?: string;
  elementName?: string;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | OnetOccupationReference
  | OnetRelatedOccupationItem
  | OnetContentModelElementReference
  | OnetScaleReference
  | OnetRatingCategoryReference
  | OnetRatingItem
  | OnetWorkStyleItem
  | OnetSoftwareSkillItem
  | OnetJobTitleItem
  | OnetTaskItem
  | OnetJobZoneReference
  | OnetOccupation
  | OnetLevelScaleAnchor
  | OnetRatingCategory
  | OnetJobZone
  | OnetScale
  | OnetContentModelElement
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;
